apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeharbor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: instance-ip.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codeharbor-service
            port:
              number: 80
status:
  loadBalancer:
    ingress:
    - ip: 172.18.0.100