name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Verify on Debian instance
      env:
        DOCKER_SERVER: ghcr.io
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ssh -o StrictHostKeyChecking=no debian@instance-ip << EOF
          export DOCKER_SERVER=ghcr.io
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          kubectl create secret docker-registry ghcr-credentials \
            --docker-server=\$DOCKER_SERVER \
            --docker-username=\$DOCKER_USERNAME \
            --docker-password=\$DOCKER_PASSWORD
          kubectl apply -f /home/debian/codeharbor.yaml
