name: Deploy avec Terraform

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ./kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
      working-directory: Terraform-Harbor

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
      working-directory: Terraform-Harbor
