name: Deploy avec Terraform

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ${{ github.workspace }}/kubeconfig
        echo "Decoded kubeconfig file content:"
        cat ${{ github.workspace }}/kubeconfig
      working-directory: Terraform-Harbor

    - name: Verify Kubeconfig
      run: |
        cat ${{ github.workspace }}/kubeconfig
      working-directory: Terraform-Harbor

    - name: Debug Kubeconfig
      run: |
        ls -l ${{ github.workspace }}/kubeconfig
        echo "Kubeconfig file size:"
        wc -l ${{ github.workspace }}/kubeconfig
      working-directory: Terraform-Harbor

    - name: Debug Kubeconfig Server Endpoint
      run: |
        grep 'server:' ${{ github.workspace }}/kubeconfig

    - name: Test Kubernetes Connection (Detailed)
      run: |
        kubectl --kubeconfig=${{ github.workspace }}/kubeconfig cluster-info
        kubectl --kubeconfig=${{ github.workspace }}/kubeconfig config view

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform plan
        terraform apply -auto-approve
      working-directory: Terraform-Harbor
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig