name: Deploy avec Terraform

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      working-directory: Terraform-Harbor

    - name: Terraform Apply
      env:
        K8S_HOST: ${{ secrets.K8S_HOST }}
        K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
        K8S_CLUSTER_CA_CERTIFICATE: ${{ secrets.K8S_CLUSTER_CA_CERTIFICATE }}
      run: |
        echo "$KUBECONFIG" | base64 -d > ./kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        terraform plan
        terraform apply -auto-approve
      working-directory: Terraform-Harbor
